# Generated by Django 5.0.7 on 2024-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category Name', models.CharField(help_text='It is the name of the expense category', max_length=50, unique=True, verbose_name='Category Name')),
                ('Category Short Description', models.CharField(blank=True, help_text='It is the short descipription of the expense category', max_length=250, verbose_name='Category Short Description')),
                ('Category Description', models.TextField(blank=True, help_text='It is the description of the expense category', max_length=1000, verbose_name='Category Description')),
                ('Activation Status Of The Category', models.BooleanField(default=True, help_text='It is the activation status of the expense category', verbose_name='Activation Status Of The Category')),
                ('Category Creation Date Time', models.DateTimeField(auto_now=True, verbose_name='Category Creation Date Time')),
                ('Category Update Date Time', models.DateTimeField(auto_now_add=True, verbose_name='Category Update Date Time')),
            ],
            options={
                'verbose_name': 'ExpenseCategory',
                'verbose_name_plural': 'ExpenseCategories',
                'ordering': ['-id'],
            },
        ),
    ]
