# Generated by Django 5.0.7 on 2024-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='Category Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='Category Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='Category Short Description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='Activation Status Of The Category',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='Category Creation Date Time',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text="It is the category's creation date and time", verbose_name='Category Creation Date Time'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='Category Update Date Time',
            field=models.DateTimeField(auto_now_add=True, help_text="It is the category's update date and time", verbose_name='Category Update Date Time'),
        ),
    ]
