# Generated by Django 5.0.7 on 2024-08-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_rename_category_description_expensecategory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='Category Update Date Time',
            new_name='updated_at',
        ),
    ]
