# Generated by Django 5.0.7 on 2024-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_rename_category_update_date_time_expensecategory_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It is the name of the expense sub category', max_length=50, unique=True, verbose_name='Name')),
                ('short_description', models.CharField(blank=True, help_text='It is the short descipription of the expense sub category', max_length=250, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='It is the description of the expense sub category', max_length=1000, verbose_name='Description')),
                ('status', models.BooleanField(default=True, help_text='It is the activation status of the expense sub category', verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now=True, help_text="It is the category's create date and time", verbose_name='Create Date Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text="It is the category's update date and time", verbose_name='Update Date Time')),
            ],
            options={
                'verbose_name': 'ExpenseCategory',
                'verbose_name_plural': 'ExpenseCategories',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text="It is the category's create date and time", verbose_name='Create Date Time'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, help_text='It is the description of the expense category', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(help_text='It is the name of the expense category', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='short_description',
            field=models.CharField(blank=True, help_text='It is the short descipription of the expense category', max_length=250, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='status',
            field=models.BooleanField(default=True, help_text='It is the activation status of the expense category', verbose_name='Activation Status'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text="It is the category's update date and time", verbose_name='Update Date Time'),
        ),
    ]
