# Generated by Django 5.0.7 on 2024-08-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_alter_expensesubcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesubcategory',
            name='category',
            field=models.ForeignKey(help_text='This is the category of the sub category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_sub_category', to='expense_app.expensecategory', verbose_name='Category'),
        ),
    ]
