# Generated by Django 5.0.7 on 2024-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0006_expensesubcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It is the name of the person', max_length=50, unique=True, verbose_name='Name')),
                ('short_description', models.CharField(blank=True, help_text='It is the short description of the person', max_length=250, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='It is the description of the person', max_length=1000, verbose_name='Description')),
                ('status', models.BooleanField(default=True, help_text='It is the activation status of the person', verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now=True, help_text="It is the category's create date and time", verbose_name='Create Date Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text="It is the category's update date and time", verbose_name='Update Date Time')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='short_description',
            field=models.CharField(blank=True, help_text='It is the short description of the expense category', max_length=250, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='expensesubcategory',
            name='short_description',
            field=models.CharField(blank=True, help_text='It is the short description of the expense sub category', max_length=250, verbose_name='Short Description'),
        ),
    ]
