# Generated by Django 5.0.7 on 2024-08-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0007_person_alter_expensecategory_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It is the name of the account', max_length=50, unique=True, verbose_name='Name')),
                ('account_number', models.CharField(help_text='It is the account number', max_length=50, unique=True, verbose_name='Name')),
                ('short_description', models.CharField(blank=True, help_text='It is the short description of the account', max_length=250, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='It is the description of the account', max_length=1000, verbose_name='Description')),
                ('status', models.BooleanField(default=True, help_text='It is the activation status of the account', verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now=True, help_text="It is the accounts's create date and time", verbose_name='Create Date Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text="It is the accounts's update date and time", verbose_name='Update Date Time')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='expensesubcategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text="It is the sub category's create date and time", verbose_name='Create Date Time'),
        ),
        migrations.AlterField(
            model_name='expensesubcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text="It is the sub category's update date and time", verbose_name='Update Date Time'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text="It is the person's create date and time", verbose_name='Create Date Time'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text="It is the person's update date and time", verbose_name='Update Date Time'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50)),
                ('name', models.CharField(help_text='It is the name of the card', max_length=50, unique=True, verbose_name='Name')),
                ('short_description', models.CharField(blank=True, help_text='It is the short description of the card', max_length=250, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='It is the description of the card', max_length=1000, verbose_name='Description')),
                ('status', models.BooleanField(default=True, help_text='It is the activation status of the card', verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now=True, help_text="It is the card's create date and time", verbose_name='Create Date Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text="It is the card's update date and time", verbose_name='Update Date Time')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='expense_app.account')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, help_text='Enter the expense amount', verbose_name='Amount')),
                ('transaction_id', models.CharField(blank=True, help_text='Enter the transaction ID', max_length=100, verbose_name='Transaction ID')),
                ('benificiary', models.CharField(blank=True, help_text='Enter the name of the beficiary', max_length=100, verbose_name='Benificary Name')),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('demand_draft', 'Demand Draft'), ('upi', 'UPI'), ('net_banking', 'Net Banking')], max_length=50, verbose_name='Expense Mode')),
                ('short_description', models.CharField(blank=True, help_text='It is the short description of the account', max_length=250, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='It is the description of the account', max_length=1000, verbose_name='Description')),
                ('status', models.BooleanField(default=True, help_text='It is the activation status of the account', verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now=True, help_text="It is the expense's create date and time", verbose_name='Create Date Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text="It is the expense's update date and time", verbose_name='Update Date Time')),
                ('account', models.ForeignKey(blank=True, help_text='Account from which expense occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='expense_app.account')),
                ('category', models.ForeignKey(help_text='Category name of the expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='expense_app.expensecategory', verbose_name='Category')),
                ('person', models.ForeignKey(blank=True, help_text='Person for which expense occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='expense_app.person')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-id'],
            },
        ),
    ]
